stages:
  - test

shellcheck-job:
  stage: test
  image: koalaman/shellcheck-alpine:stable
  script:
    - echo "Running shellcheck on all .sh files..."
    - shellcheck --version
    - find . -type f -name "*.sh" -exec shellcheck {} +
    - echo "Shellcheck completed successfully!"
