stages:
  - test

shellcheck-job:
  stage: test
  image: alpine:latest
  before_script:
    - apk add --no-cache shellcheck
  script:
    - echo "Running shellcheck on all .sh files..."
    - shellcheck --version
    - find . -type f -name "*.sh" -exec shellcheck {} +
    - echo "Shellcheck completed successfully!"
